### ISSUE TITLE
RYB_ITTEN_NEUTRAL colors swapped

### ISSUE THREAD

**Issue by dirx** [meodai/RYBitten#1]
Hi @meodai,

in the RYB_ITTEN_NEUTRAL cube it looks like values for red, yellow and pink, green are swapped.

<img width="378" alt="image" src="https://github.com/meodai/RYBitten/assets/795259/91cf6de4-5772-4083-a806-2184bf297a65">

btw: great lib.

**Comment by meodai** [comment]
thanks
