### ISSUE TITLE
Add types declarations to package.json

### ISSUE THREAD

**Issue by dirx** [meodai/RYBitten#2]
A reference to the type declarations is missing in the package.json @ top level.

```
"types": "./dist/main.d.ts"
```

See https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by meodai** [comment]
have you tested that? Because it does not import the types correctly if I don't have them where they are right now. At least using vite.js

**Comment by dirx** [comment]
In my current app tsconfig setup (`moduleResolution: "node"`) the type declarations could not be resolved without it.

The "export.types" should stay. Just adding the same on top level should do the trick.

Plus: I could not directly use any types from the cubes.d.ts. I wonder if they are part of the public interface of the library. If no, then it might be helpful to provide only the public types in main.d.ts and drop the other *.d.ts files in the dist package 
 (eg with `dts({ rollupTypes: true }`).

**Comment by meodai** [comment]
hmmm I did not try to import the cube types in ts yet. Il try it when I am done with the demo page, thanks for the PRs @dirx
